name: help

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.1.3

  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
